In [1]:
import os
import pandas as pd
import numpy as np

In [2]:
os.getcwd()

'E:\\SLIIT-research\\Project'

In [3]:
from preprocessing.training_pipeline import DataPreprocessingPipeline

In [4]:
dpp = DataPreprocessingPipeline()

In [5]:
df = pd.read_csv("data\\sampled_dataset.csv")

In [6]:
df.head()

,Unnamed: 0,Flow ID,Src IP,Src Port,Dst IP,Dst Port,Protocol,Timestamp,Flow Duration,Tot Fwd Pkts,...,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,4150500,172.31.0.2-172.31.66.75-53-51217-17,172.31.66.75,51217,172.31.0.2,53,17,20/02/2018 03:49:40,1472,1,...,8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
1,5392007,172.31.0.2-172.31.68.23-53-63406-17,172.31.68.23,63406,172.31.0.2,53,17,20/02/2018 02:42:09,2680,1,...,8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
2,5131917,172.31.67.91-74.125.29.156-50056-443-6,172.31.67.91,50056,74.125.29.156,443,6,20/02/2018 08:55:45,333,3,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
3,513616,172.31.69.28-18.219.9.1-80-57274-6,18.219.9.1,57274,172.31.69.28,80,6,21/02/2018 11:55:44 PM,3689,1,...,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,ddos
4,838044,172.31.69.25-18.219.193.20-80-44560-6,18.219.193.20,44560,172.31.69.25,80,6,16/02/2018 11:20:43 PM,136,1,...,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,ddos

In [7]:
y = df['Label']
X = df.drop(columns='Label')

In [8]:
from preprocessing.feature_dropper import FeatureDropper
dropper = FeatureDropper()

In [9]:
X_dropped = dropper.fit_transform(X)

In [10]:
from preprocessing.composite_splitter import CompositeSplitter
splitter = CompositeSplitter()

In [11]:
splitted_X = splitter.fit_transform(X_dropped)

hi
hi

In [12]:
splitted_X

,Src Port,Dst Port,Protocol,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,...,Idle Max,Idle Min,Src IP_octet1,Src IP_octet2,Src IP_octet3,Src IP_octet4,Dst IP_octet1,Dst IP_octet2,Dst IP_octet3,Dst IP_octet4
0,51217,53,17,1472,1,1,40.0,139.0,40.0,40.0,...,0.0,0.0,172,31,66,75,172,31,0,2
1,63406,53,17,2680,1,1,42.0,142.0,42.0,42.0,...,0.0,0.0,172,31,68,23,172,31,0,2
2,50056,443,6,333,3,0,77.0,0.0,46.0,0.0,...,0.0,0.0,172,31,67,91,74,125,29,156
3,57274,80,6,3689,1,1,0.0,0.0,0.0,0.0,...,0.0,0.0,18,219,9,1,172,31,69,28
4,44560,80,6,136,1,1,0.0,0.0,0.0,0.0,...,0.0,0.0,18,219,193,20,172,31,69,25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,62181,80,6,1827,1,1,0.0,0.0,0.0,0.0,...,0.0,0.0,18,219,9,1,172,31,69,28
196,49492,53,17,515,1,1,44.0,72.0,44.0,44.0,...,0.0,0.0,172,31,67,83,172,31,0,2
197,51092,443,6,1823,1,1,0.0,0.0,0.0,0.0,...,0.0,0.0,172,31,66,111,93,184,216,180
198,56099,80,6,1039,1,1,0.0,0.0,0.0,0.0,...,0.0,0.0,18,219,32,43,172,31,69,28
199,61190,53,17,94682,2,2,62.0,216.0,31.0,31.0,...,0.0,0.0,172,31,67,94,172,31,0,2

In [13]:
# splitted_X[['Dst IP_octet3', 'Dst IP_octet4']] = splitted_X[['Dst IP_octet3', 'Dst IP_octet4']].apply(pd.to_numeric, errors='coerce')

In [14]:
from preprocessing.numerical_standardiser import NumericalStandardiser
std = NumericalStandardiser()

In [15]:
std.fit_transform(splitted_X)

,Src Port,Dst Port,Protocol,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,...,Idle Max,Idle Min,Src IP_octet1,Src IP_octet2,Src IP_octet3,Src IP_octet4,Dst IP_octet1,Dst IP_octet2,Dst IP_octet3,Dst IP_octet4
0,0.505277,-0.573030,2.366876,-0.322704,-0.468008,-0.500989,-0.231767,-0.229571,-0.434785,2.399053,...,-0.263525,-0.260096,0.759348,-0.801019,-0.425706,0.164059,0.542298,-0.657555,-1.287042,-0.796040
1,1.007933,-0.573030,2.366876,-0.322656,-0.468008,-0.500989,-0.230528,-0.228386,-0.431024,2.539595,...,-0.263525,-0.260096,0.759348,-0.801019,-0.392648,-0.704685,0.542298,-0.657555,-1.287042,-0.796040
2,0.457399,-0.555176,-0.408778,-0.322749,-0.118096,-0.726153,-0.208837,-0.284484,-0.423502,-0.411788,...,-0.263525,-0.260096,0.759348,-0.801019,-0.409177,0.431365,-0.977874,0.457146,-0.855623,1.464312
3,0.755059,-0.571794,-0.408778,-0.322616,-0.468008,-0.500989,-0.256556,-0.284484,-0.510002,-0.411788,...,-0.263525,-0.260096,-1.361620,1.324330,-1.367863,-1.072230,0.542298,-0.657555,-0.260562,-0.414422
4,0.230753,-0.571794,-0.408778,-0.322757,-0.468008,-0.500989,-0.256556,-0.284484,-0.510002,-0.411788,...,-0.263525,-0.260096,-1.361620,1.324330,1.673486,-0.754805,0.542298,-0.657555,-0.260562,-0.458455
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,0.957416,-0.571794,-0.408778,-0.322690,-0.468008,-0.500989,-0.256556,-0.284484,-0.510002,-0.411788,...,-0.263525,-0.260096,-1.361620,1.324330,-1.367863,-1.072230,0.542298,-0.657555,-0.260562,-0.414422
196,0.434141,-0.573030,2.366876,-0.322742,-0.468008,-0.500989,-0.229288,-0.256040,-0.427263,2.680137,...,-0.263525,-0.260096,0.759348,-0.801019,-0.409177,0.297712,0.542298,-0.657555,-1.287042,-0.796040
197,0.500122,-0.555176,-0.408778,-0.322690,-0.468008,-0.500989,-0.256556,-0.284484,-0.510002,-0.411788,...,-0.263525,-0.260096,0.759348,-0.801019,-0.425706,0.765497,-0.683146,1.156799,1.926287,1.816575
198,0.706603,-0.571794,-0.408778,-0.322721,-0.468008,-0.500989,-0.256556,-0.284484,-0.510002,-0.411788,...,-0.263525,-0.260096,-1.361620,1.324330,-0.987695,-0.370553,0.542298,-0.657555,-0.260562,-0.414422
199,0.916548,-0.573030,2.366876,-0.319013,-0.293052,-0.275826,-0.218133,-0.199152,-0.451709,1.766614,...,-0.263525,-0.260096,0.759348,-0.801019,-0.409177,0.481484,0.542298,-0.657555,-1.287042,-0.796040

In [16]:
std_X = std.fit_transform(splitted_X)

In [17]:
pd.isna(std_X).sum()

Src Port         0
Dst Port         0
Protocol         0
Flow Duration    0
Tot Fwd Pkts     0
                ..
Src IP_octet4    0
Dst IP_octet1    0
Dst IP_octet2    0
Dst IP_octet3    0
Dst IP_octet4    0
Length: 87, dtype: int64

In [19]:
dpp.fit_transform(X)

,Src IP,Src Port,Dst IP,Dst Port,Protocol,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,...,Fwd Act Data Pkts,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min
0,172.31.66.75,51217,172.31.0.2,53,17,1472,1,1,40.0,139.0,...,0,8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,172.31.68.23,63406,172.31.0.2,53,17,2680,1,1,42.0,142.0,...,0,8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,172.31.67.91,50056,74.125.29.156,443,6,333,3,0,77.0,0.0,...,1,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,18.219.9.1,57274,172.31.69.28,80,6,3689,1,1,0.0,0.0,...,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,18.219.193.20,44560,172.31.69.25,80,6,136,1,1,0.0,0.0,...,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,18.219.9.1,62181,172.31.69.28,80,6,1827,1,1,0.0,0.0,...,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
196,172.31.67.83,49492,172.31.0.2,53,17,515,1,1,44.0,72.0,...,0,8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
197,172.31.66.111,51092,93.184.216.180,443,6,1823,1,1,0.0,0.0,...,0,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
198,18.219.32.43,56099,172.31.69.28,80,6,1039,1,1,0.0,0.0,...,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
199,172.31.67.94,61190,172.31.0.2,53,17,94682,2,2,62.0,216.0,...,1,8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [50]:
dpp.save("preprocessor\\sampled_dataset_preprocessor_model.pkl")

['kh.pkl']