In [2]:
import pandas as pd
import numpy as np

In [56]:
cols = ['Unnamed: 0',
 'Flow ID',
 'Src IP',
 'Src Port',
 'Dst IP',
 'Dst Port',
 'Protocol',
 'Timestamp',
 'Flow Duration',
 'Tot Fwd Pkts',
 'Tot Bwd Pkts',
 'TotLen Fwd Pkts',
 'TotLen Bwd Pkts',
 'Fwd Pkt Len Max',
 'Fwd Pkt Len Min',
 'Fwd Pkt Len Mean',
 'Fwd Pkt Len Std',
 'Bwd Pkt Len Max',
 'Bwd Pkt Len Min',
 'Bwd Pkt Len Mean',
 'Bwd Pkt Len Std',
 'Flow Byts/s',
 'Flow Pkts/s',
 'Flow IAT Mean',
 'Flow IAT Std',
 'Flow IAT Max',
 'Flow IAT Min',
 'Fwd IAT Tot',
 'Fwd IAT Mean',
 'Fwd IAT Std',
 'Fwd IAT Max',
 'Fwd IAT Min',
 'Bwd IAT Tot',
 'Bwd IAT Mean',
 'Bwd IAT Std',
 'Bwd IAT Max',
 'Bwd IAT Min',
 'Fwd PSH Flags',
 'Bwd PSH Flags',
 'Fwd URG Flags',
 'Bwd URG Flags',
 'Fwd Header Len',
 'Bwd Header Len',
 'Fwd Pkts/s',
 'Bwd Pkts/s',
 'Pkt Len Min',
 'Pkt Len Max',
 'Pkt Len Mean',
 'Pkt Len Std',
 'Pkt Len Var',
 'FIN Flag Cnt',
 'SYN Flag Cnt',
 'RST Flag Cnt',
 'PSH Flag Cnt',
 'ACK Flag Cnt',
 'URG Flag Cnt',
 'CWE Flag Count',
 'ECE Flag Cnt',
 'Down/Up Ratio',
 'Pkt Size Avg',
 'Fwd Seg Size Avg',
 'Bwd Seg Size Avg',
 'Fwd Byts/b Avg',
 'Fwd Pkts/b Avg',
 'Fwd Blk Rate Avg',
 'Bwd Byts/b Avg',
 'Bwd Pkts/b Avg',
 'Bwd Blk Rate Avg',
 'Subflow Fwd Pkts',
 'Subflow Fwd Byts',
 'Subflow Bwd Pkts',
 'Subflow Bwd Byts',
 'Init Fwd Win Byts',
 'Init Bwd Win Byts',
 'Fwd Act Data Pkts',
 'Fwd Seg Size Min',
 'Active Mean',
 'Active Std',
 'Active Max',
 'Active Min',
 'Idle Mean',
 'Idle Std',
 'Idle Max',
 'Idle Min',
 'Label']

In [64]:
# df1 = pd.read_csv("/kaggle/input/ddos-datasets/ddos_balanced/final_dataset.csv", nrows=1000000, skiprows=50000000, names=cols)

In [66]:
chunks = []
chunk_size = 50000

for chunk in pd.read_csv("/kaggle/input/ddos-datasets/ddos_balanced/final_dataset.csv", chunksize=chunk_size):
    chunk_ = chunk.sample(frac=0.05, random_state=42)
    chunks.append(chunk_)

In [67]:
df = pd.concat(chunks, ignore_index=True)

In [71]:
df["Label"].value_counts()

Label
ddos      323647
Benign    316084
Name: count, dtype: int64

In [72]:
df.to_csv('/kaggle/working/sample_data.csv', index=False)

In [73]:
df.head()

,Unnamed: 0,Flow ID,Src IP,Src Port,Dst IP,Dst Port,Protocol,Timestamp,Flow Duration,Tot Fwd Pkts,...,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,150754,192.168.56.1-97.74.144.108-36855-80-6,192.168.56.1,36855,97.74.144.108,80,6,13/06/2010 12:23:17 AM,26545238,5,...,0,4331.333333,7495.161795,12986.0,1.0,8843684.0,1.191166e+06,10186083.0,7912967.0,ddos
1,49247,192.168.56.1-67.220.214.50-36818-80-6,192.168.56.1,36818,67.220.214.50,80,6,12/06/2010 02:36:17 PM,24975333,5,...,0,4255.000000,7358.617873,12752.0,6.0,8320671.0,2.212232e+06,10186104.0,5876634.0,ddos
2,1638,192.168.2.108-74.55.1.4-1253-80-6,192.168.2.108,1253,74.55.1.4,80,6,12/06/2010 08:47:02 AM,5030987,1,...,0,0.000000,0.000000,0.0,0.0,0.0,0.000000e+00,0.0,0.0,ddos
3,54404,192.168.2.109-203.73.24.75-1555-80-6,192.168.2.109,1555,203.73.24.75,80,6,12/06/2010 02:45:57 PM,303,2,...,0,0.000000,0.000000,0.0,0.0,0.0,0.000000e+00,0.0,0.0,ddos
4,199244,192.168.2.109-203.73.24.75-4227-80-6,192.168.2.109,4227,203.73.24.75,80,6,13/06/2010 07:38:02 AM,292,2,...,0,0.000000,0.000000,0.0,0.0,0.0,0.000000e+00,0.0,0.0,ddos

In [74]:
df.columns.tolist()

['Unnamed: 0',
 'Flow ID',
 'Src IP',
 'Src Port',
 'Dst IP',
 'Dst Port',
 'Protocol',
 'Timestamp',
 'Flow Duration',
 'Tot Fwd Pkts',
 'Tot Bwd Pkts',
 'TotLen Fwd Pkts',
 'TotLen Bwd Pkts',
 'Fwd Pkt Len Max',
 'Fwd Pkt Len Min',
 'Fwd Pkt Len Mean',
 'Fwd Pkt Len Std',
 'Bwd Pkt Len Max',
 'Bwd Pkt Len Min',
 'Bwd Pkt Len Mean',
 'Bwd Pkt Len Std',
 'Flow Byts/s',
 'Flow Pkts/s',
 'Flow IAT Mean',
 'Flow IAT Std',
 'Flow IAT Max',
 'Flow IAT Min',
 'Fwd IAT Tot',
 'Fwd IAT Mean',
 'Fwd IAT Std',
 'Fwd IAT Max',
 'Fwd IAT Min',
 'Bwd IAT Tot',
 'Bwd IAT Mean',
 'Bwd IAT Std',
 'Bwd IAT Max',
 'Bwd IAT Min',
 'Fwd PSH Flags',
 'Bwd PSH Flags',
 'Fwd URG Flags',
 'Bwd URG Flags',
 'Fwd Header Len',
 'Bwd Header Len',
 'Fwd Pkts/s',
 'Bwd Pkts/s',
 'Pkt Len Min',
 'Pkt Len Max',
 'Pkt Len Mean',
 'Pkt Len Std',
 'Pkt Len Var',
 'FIN Flag Cnt',
 'SYN Flag Cnt',
 'RST Flag Cnt',
 'PSH Flag Cnt',
 'ACK Flag Cnt',
 'URG Flag Cnt',
 'CWE Flag Count',
 'ECE Flag Cnt',
 'Down/Up Ratio',
 'Pkt Size Avg',
 'Fwd Seg Size Avg',
 'Bwd Seg Size Avg',
 'Fwd Byts/b Avg',
 'Fwd Pkts/b Avg',
 'Fwd Blk Rate Avg',
 'Bwd Byts/b Avg',
 'Bwd Pkts/b Avg',
 'Bwd Blk Rate Avg',
 'Subflow Fwd Pkts',
 'Subflow Fwd Byts',
 'Subflow Bwd Pkts',
 'Subflow Bwd Byts',
 'Init Fwd Win Byts',
 'Init Bwd Win Byts',
 'Fwd Act Data Pkts',
 'Fwd Seg Size Min',
 'Active Mean',
 'Active Std',
 'Active Max',
 'Active Min',
 'Idle Mean',
 'Idle Std',
 'Idle Max',
 'Idle Min',
 'Label']

In [75]:
df.drop(columns=["Unnamed: 0", "Flow ID", "Timestamp", "Src IP", "Dst IP"], inplace=True)

In [76]:
columns_with_nan = df.columns[df.isnull().any()]

for col in columns_with_nan:
    print(f"Column '{col}' has {df[col].isnull().sum()} NaN values")

Column 'Flow Byts/s' has 1454 NaN values

In [33]:
# columns_with_inf = df1.columns[np.isinf(train_X).any()]

# for col in columns_with_inf:
#     print(f"Column '{col}' has {df1[col].isnull().sum()} INF values")

IndexError: boolean index did not match indexed array along dimension 0; dimension is 80 but corresponding boolean dimension is 79

In [77]:
df.replace([np.inf, -np.inf], np.nan, inplace=True)

In [78]:
df = pd.DataFrame(df.dropna(), columns=df.columns)

In [79]:
y = df["Label"]
X = df.drop(columns=["Label"])

In [47]:
y.nunique()

1

In [80]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from sklearn.model_selection import train_test_split

In [81]:
train_X, test_X, train_y, test_y = train_test_split(X, y, test_size=0.2)

In [82]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(strategy="mean")
train_X = pd.DataFrame(imputer.fit_transform(train_X), columns=train_X.columns)
test_X = pd.DataFrame(imputer.transform(test_X), columns=test_X.columns)

In [83]:
scaler = MinMaxScaler()
train_scaled = scaler.fit_transform(train_X)
train_X = pd.DataFrame(train_scaled, columns=train_X.columns, index=train_X.index)

In [84]:
test_X = pd.DataFrame(scaler.transform(test_X), columns=test_X.columns, index=test_X.index)

In [85]:
train_X.head()

,Src Port,Dst Port,Protocol,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,...,Fwd Act Data Pkts,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min
0,0.006790,0.957137,0.352941,2.000000e-07,0.000009,0.000000,0.000000,0.000000,0.000000,0.0,...,0.000000,0.454545,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,0.820539,0.006760,0.352941,9.776659e-01,0.000077,0.000058,0.000219,0.000011,0.025813,0.0,...,0.000045,0.454545,0.000624,0.00014,0.000687,0.000560,0.488126,0.007722,0.491547,0.484705
2,0.647959,0.001221,0.352941,4.355417e-04,0.000009,0.000003,0.000000,0.000000,0.000000,0.0,...,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,0.652323,0.001221,0.352941,3.567084e-04,0.000005,0.000003,0.000000,0.000000,0.000000,0.0,...,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,0.767010,0.001221,0.352941,6.161862e-01,0.000050,0.000041,0.000076,0.000003,0.018450,0.0,...,0.000045,0.454545,0.000373,0.00014,0.000564,0.000278,0.083712,0.000787,0.084784,0.083379

In [87]:
train_y = train_y.map({"Benign": 0, "ddos": 1})

In [90]:
test_y = test_y.map({"Benign": 0, "ddos": 1})

In [89]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(max_iter=1000, random_state=42)
model.fit(train_X, train_y)

LogisticRegression(max_iter=1000, random_state=42)

In [91]:
y_pred = model.predict(test_X)

In [93]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [95]:
train_X.shape, test_X.shape

((509895, 79), (127474, 79))

In [94]:
print("Accuracy:", accuracy_score(test_y, y_pred))
print("\nClassification Report:\n", classification_report(test_y, y_pred))

Accuracy: 0.9827258892009351

Classification Report:
               precision    recall  f1-score   support

           0       0.98      0.98      0.98     62742
           1       0.98      0.98      0.98     64732

    accuracy                           0.98    127474
   macro avg       0.98      0.98      0.98    127474
weighted avg       0.98      0.98      0.98    127474